language: python
python:
  - "3.3" 
script:
- python manage.py makemigrations
- python manage.py migrate
- python manage.py test Login Reconhecimentos
deploy:
  provider: openshift
  user: gimoteco@gmail.com
  password:
    secure: B1jMTJaML3PaQNbgqJLPr5GWCxjI22TcedicfHS8li0u3r607deiWutpnWu/4E5Ov4jD1TaMuWW27i8LH5/Q5bzqPOBrnU1XBgv6MJeazsx3rLCACTjaAQSinYcVjy8zuLJTThL9/K0Fhgju3Sy8Z2GrjbPD+PrkuI0bY3h08R8xviGEpXF2SyK65VWXynExZD9Uf+u3/DFsyIRuPapRxYGkEaFkDDwU8N7I1s7HdZpCjTsLdAgf0F8PhLW7JiroZfpvEuQjb5p8zHZ0ar7fwno1t/KYzMI3h2jGHPHzp3PD4ZZGf1a4YpeHtlAW50o8BmSqHOExmoEPANI3F1zFz0rGd+XENxDc4vK63Rxlvtam9KfOJF3VHis3mYtD0aWi1NykW2T6awS7fbVY+Tmx3tGTyRY9qq+EsHVEiRBgXFw2fPBCuqXxP9FbBZXn9MHfXvGplE7yLLbJI1vevhhuIbsz7K+H6cJF0tUHbgI6C0YHcAm5neQTV0KlUmxIlPA4JRzvoEiPwXwzepAWnY8JD6uzjlYihBuL8gjBPoJQsccXoM9JagCVQVhxtpibCgDfxfZGB7IRneu+pQ/tBFpFCJnJdNvB9P7z6wAdKGmKxRkHHGLId/3+R7RT2Lf2CkKWzG/FatlgTyNLGzUdnkuZTjDnrGGUWDipnkQQu8Wjoo0=
  app: valorometro3
  domain: cafecombytes
  on:
    repo: DigithoBrasil/Valorometro
    branch: python3
notifications:
  slack:
    secure: sGNzCxPD2NPZJiZ2zYda0tJfaRjQck5wUiK2uQmR5uVWkB5S9+iWPnl2pQkJt3LjlcuRzDAfRm44MNa8WL/VKiwUneEOmCk7dwooRmXavxLkh01UgkcRvXSr7xt+gW2mQNH4d/Q2JW6eAhHr/n3ffhDu8ZlzZfBpN9OljE/BeZRYGWqjaQ4dsbabFbidF+r44pLXN38Q7r5bkmCTm8hijQEUtrtnCcI8gZ1xOFAk/hmsxxTVFgiqgiExsyphdEJ5re+lmg9aDnsGk0iXsMgaFjaPpqqU1Eqyd45TFjKkmWPa4Dx4H7thlbbazObFUB539ygYqdG9PFJ5/llpsRYcLkp+jx8YJD6OcGnlavA8+aoWH9yZiJECb8hZVmNSuLyHx8WYpOvIHp6F7+rhwqOBTp8H8C0U5IDEACyV6LpGwvjPs8Fkh/MWaqKlHG/SFaqsoIDQbzufnxg959Rb2Jld0mQa6+IDrGC+e8xFVe2v1u4x5xthJWDzrAmB0t0HdtgSNb/+tRCMgDiCM0yIFNHoLxsFX02eXX2SRGLjmmRQY5jiMby1cH0jc6bnqgDpaBIvFG1uvTLrrP318v9UpZoCJVcjXVgp5DE0cJ4/PWL9PYgiuWVxl+D9i9nbrGvYviF9gdRDAsRX4ygUJb1wfHgtMWQKp+rtNI4LoltnmH4Sg7k=
after_deploy:
- python manage.py test Valorometro.testes_de_fumaca
