language: python
python:
- '3.3'
script:
- python manage.py makemigrations
- python manage.py migrate
- python manage.py test Login Reconhecimentos
notifications:
  slack:
    secure: sGNzCxPD2NPZJiZ2zYda0tJfaRjQck5wUiK2uQmR5uVWkB5S9+iWPnl2pQkJt3LjlcuRzDAfRm44MNa8WL/VKiwUneEOmCk7dwooRmXavxLkh01UgkcRvXSr7xt+gW2mQNH4d/Q2JW6eAhHr/n3ffhDu8ZlzZfBpN9OljE/BeZRYGWqjaQ4dsbabFbidF+r44pLXN38Q7r5bkmCTm8hijQEUtrtnCcI8gZ1xOFAk/hmsxxTVFgiqgiExsyphdEJ5re+lmg9aDnsGk0iXsMgaFjaPpqqU1Eqyd45TFjKkmWPa4Dx4H7thlbbazObFUB539ygYqdG9PFJ5/llpsRYcLkp+jx8YJD6OcGnlavA8+aoWH9yZiJECb8hZVmNSuLyHx8WYpOvIHp6F7+rhwqOBTp8H8C0U5IDEACyV6LpGwvjPs8Fkh/MWaqKlHG/SFaqsoIDQbzufnxg959Rb2Jld0mQa6+IDrGC+e8xFVe2v1u4x5xthJWDzrAmB0t0HdtgSNb/+tRCMgDiCM0yIFNHoLxsFX02eXX2SRGLjmmRQY5jiMby1cH0jc6bnqgDpaBIvFG1uvTLrrP318v9UpZoCJVcjXVgp5DE0cJ4/PWL9PYgiuWVxl+D9i9nbrGvYviF9gdRDAsRX4ygUJb1wfHgtMWQKp+rtNI4LoltnmH4Sg7k=
deploy:
  provider: openshift
  user: renan.siravegna@gmail.com
  password:
    secure: qFocdaVrovBjfLpZd3W9fMM20DhC4ji83AztgQKkufxZtCVs8zsWK3Na/KDXVVMpzCQDqPJaWY7daiFjwoEFy9//zF8Y3lacuycfF8arTl5c/C3D1HlExBWOdsZFCBtFfAEJtgTWHc/jo9MNF3AXX4jiUh13tU/95WrCMZiuZFSni341tR9mtcfgmQQU/LJ5QS14y3mbm/iyjvM/XZrVg6/Ewg6DqFHW+0Cin+ftXPYP9KQuSpMBk5xpJWDjXtXk87RNAI4LvSk+YFqUjzvfgPc9Cfay9RqB02DnhRJX2GgmZVwnQgkKh3uMJG8JZECm9GGsd/ONoh9HvP5y1IaGsYf/6SI2c+6JcNEKJSQb1aIuPB+r35i9cesFuVVA6PexzR5V1bj9KbruzM7oBElYPWrC27uVIE5uzVj4vF9fg9ubi9vKoePevmrTbm+BOykhExXUCNBKV5qnE7uIiIBCmGukNL1k016pJIZWC9DU30pz83cnhSKuGG2rr2dKxFRxYQPSvKJxgw89vtcgOXucmm8ZDHZDpkNBbiZH1FFj2UAG/hrT3gHOQTFJeHzuZhBOf+hAz19r9wSUlKWVfzpEtTA64n1974ilbcJ6Di13cnJkGOuo9Ab8DZHmTnaXutTZmpzQfzyNSqTE016nMg66GSWApgsJPqZRnhpNr10tz+w=
  app: Aprecie
  domain: renansiravegna
  on:
    repo: DigithoBrasil/Aprecie
after_deploy:
- python manage.py test Aprecie.testes_de_fumaca
