language: python
script:
- python manage.py makemigrations
- python manage.py migrate
- python manage.py test Login Reconhecimentos
deploy:
  provider: openshift
  user: gimoteco@gmail.com
  password:
    secure: Q9u+hRgPy9QmdZf8XZCsbsWdYugIwbGKX86vE73ZjIYq2XcQkTcF79GUU8ouj3kFE6vbEICyAj3DuKql3i630UPc+RXfcZFrkVtInu1yYeyFb+zS8iOk5pf6Fs72+LQ5PbUoVoQqZj/M4dLoJACg9TUE/QLY6BSb/xvQjrU8NZogn0ZrFYkwPnIHs5MJ+C+TNaGcmQjFdIXUqJxOPFsKr7J0yyxNTmXorfRkvVrwr5jj1+6jTrl5+KWhjbyA1UEZbcloTwO2w1CT8t2BPdn6paVo172xeUNsCVvgvWuZBVSQuXvxdYIgZP+w9+87VdyfWnxEo83ahd9/1ZubaK8K5jVPkPYbdGPlt6xGy2rqIYCmMoqDiMF6XevmxMQcc/r6+YX+DjLiTi4BrpPfxhX+/Yg46NpJEE2+Zmq1HL4LcjJhsfF1OCnf2YQxPOdMMujzhWLMOo1AL1SLnnysnkdSzGOiFJq1BxbPg6CIqPQx+eHgB8W06pGHio2oBoB2wM9dskdbNfaa4eWA80gC1yQdvMBNVxpKZcefJ6l8G1Ap0t40QaFNyzBBQJ3FmVV8BRaq8XZmxwjou2NqHk6otRcktqDgewmNKzsyou+hU6UaZULCfqrn8HxfN3yioCp7mvqrzh5Mn8OsSwKU0tNVyZNxvvsr61RG4vJHwlFlNyyuq9g=
  app: Valorometro
  domain: cafecombytes
  on:
    repo: DigithoBrasil/Valorometro
notifications:
  slack:
    secure: sGNzCxPD2NPZJiZ2zYda0tJfaRjQck5wUiK2uQmR5uVWkB5S9+iWPnl2pQkJt3LjlcuRzDAfRm44MNa8WL/VKiwUneEOmCk7dwooRmXavxLkh01UgkcRvXSr7xt+gW2mQNH4d/Q2JW6eAhHr/n3ffhDu8ZlzZfBpN9OljE/BeZRYGWqjaQ4dsbabFbidF+r44pLXN38Q7r5bkmCTm8hijQEUtrtnCcI8gZ1xOFAk/hmsxxTVFgiqgiExsyphdEJ5re+lmg9aDnsGk0iXsMgaFjaPpqqU1Eqyd45TFjKkmWPa4Dx4H7thlbbazObFUB539ygYqdG9PFJ5/llpsRYcLkp+jx8YJD6OcGnlavA8+aoWH9yZiJECb8hZVmNSuLyHx8WYpOvIHp6F7+rhwqOBTp8H8C0U5IDEACyV6LpGwvjPs8Fkh/MWaqKlHG/SFaqsoIDQbzufnxg959Rb2Jld0mQa6+IDrGC+e8xFVe2v1u4x5xthJWDzrAmB0t0HdtgSNb/+tRCMgDiCM0yIFNHoLxsFX02eXX2SRGLjmmRQY5jiMby1cH0jc6bnqgDpaBIvFG1uvTLrrP318v9UpZoCJVcjXVgp5DE0cJ4/PWL9PYgiuWVxl+D9i9nbrGvYviF9gdRDAsRX4ygUJb1wfHgtMWQKp+rtNI4LoltnmH4Sg7k=
after_deploy:
  - python manage.py test Valorometro.testes_de_fumaca