language: python
python:
- '3.3'
script:
- python manage.py makemigrations
- python manage.py migrate
- python manage.py test Login Reconhecimentos
notifications:
  slack:
    secure: sGNzCxPD2NPZJiZ2zYda0tJfaRjQck5wUiK2uQmR5uVWkB5S9+iWPnl2pQkJt3LjlcuRzDAfRm44MNa8WL/VKiwUneEOmCk7dwooRmXavxLkh01UgkcRvXSr7xt+gW2mQNH4d/Q2JW6eAhHr/n3ffhDu8ZlzZfBpN9OljE/BeZRYGWqjaQ4dsbabFbidF+r44pLXN38Q7r5bkmCTm8hijQEUtrtnCcI8gZ1xOFAk/hmsxxTVFgiqgiExsyphdEJ5re+lmg9aDnsGk0iXsMgaFjaPpqqU1Eqyd45TFjKkmWPa4Dx4H7thlbbazObFUB539ygYqdG9PFJ5/llpsRYcLkp+jx8YJD6OcGnlavA8+aoWH9yZiJECb8hZVmNSuLyHx8WYpOvIHp6F7+rhwqOBTp8H8C0U5IDEACyV6LpGwvjPs8Fkh/MWaqKlHG/SFaqsoIDQbzufnxg959Rb2Jld0mQa6+IDrGC+e8xFVe2v1u4x5xthJWDzrAmB0t0HdtgSNb/+tRCMgDiCM0yIFNHoLxsFX02eXX2SRGLjmmRQY5jiMby1cH0jc6bnqgDpaBIvFG1uvTLrrP318v9UpZoCJVcjXVgp5DE0cJ4/PWL9PYgiuWVxl+D9i9nbrGvYviF9gdRDAsRX4ygUJb1wfHgtMWQKp+rtNI4LoltnmH4Sg7k=
deploy:
  - provider: openshift
    user: renan.siravegna@gmail.com
    password:
      secure: lHB5+QCwkC49ocBGPwfxY9PHf8NIl21Devf2NjgxTw0wCYiOpM+ywQCZEtp+hPtRgQ9NaIvUmZMW41RXYXNRrnbM89DtTZASvdolDyViPuC6qMgoGWUyzD4veNTfECwXOuzfRfyMxEUj1MEgR2u9yzCdN2oCOoZcTTceU8t6g/pINDET8y1bmfY5glpA/3ZFAHp+acadZ4N/wK+vDBnxxJZupL9dKLxttcBrNHEiHREPJUbtUsCJ+22Z3DecELA3iGtyByMj09xQvCriMnbIvmuqSrKI4Tgx5WGs83Hq4RMs/DFZlQGPy6l0k5BhqKW+jKwI5tkqNhBlOlOri0VnqL1ho7n7GPUct5ogwQ8eV8pHrKht4HQsF4I4yqElU+er5l6nPYyB7Be6uCtALKe6CPx37t1WL4bqhlby3PK7jpmHxb/3rGajBizJj0jfgKF8D06gavQz2P9gd7nfgfYN77/Iz05wt4BwkBgNERwVceWirlPa5DmCacu9G06WKJl3JFDGzhrMySeCxWoY75IAxIji9LDKzRg81OUvQWYahBDpWcfxYY8wcc5FlBjvhPSQ2ONLHd6Mip6I55jJc3XiQRrHsVyeLu3LoRrQoJfYbWvDDgGlcHCpEBG0JuczytEwUuW6pCLzaq0vHryt80Oa60n5yV87Dn5GOTHVZYrHaOc=
    app: apreciestaging
    domain: renansiravegna
    on:
      repo: DigithoBrasil/Aprecie
      branch: master
  - provider: openshift
    user: renan.siravegna@gmail.com
    password:
      secure: lHB5+QCwkC49ocBGPwfxY9PHf8NIl21Devf2NjgxTw0wCYiOpM+ywQCZEtp+hPtRgQ9NaIvUmZMW41RXYXNRrnbM89DtTZASvdolDyViPuC6qMgoGWUyzD4veNTfECwXOuzfRfyMxEUj1MEgR2u9yzCdN2oCOoZcTTceU8t6g/pINDET8y1bmfY5glpA/3ZFAHp+acadZ4N/wK+vDBnxxJZupL9dKLxttcBrNHEiHREPJUbtUsCJ+22Z3DecELA3iGtyByMj09xQvCriMnbIvmuqSrKI4Tgx5WGs83Hq4RMs/DFZlQGPy6l0k5BhqKW+jKwI5tkqNhBlOlOri0VnqL1ho7n7GPUct5ogwQ8eV8pHrKht4HQsF4I4yqElU+er5l6nPYyB7Be6uCtALKe6CPx37t1WL4bqhlby3PK7jpmHxb/3rGajBizJj0jfgKF8D06gavQz2P9gd7nfgfYN77/Iz05wt4BwkBgNERwVceWirlPa5DmCacu9G06WKJl3JFDGzhrMySeCxWoY75IAxIji9LDKzRg81OUvQWYahBDpWcfxYY8wcc5FlBjvhPSQ2ONLHd6Mip6I55jJc3XiQRrHsVyeLu3LoRrQoJfYbWvDDgGlcHCpEBG0JuczytEwUuW6pCLzaq0vHryt80Oa60n5yV87Dn5GOTHVZYrHaOc=
    app: aprecie
    domain: renansiravegna
    on:
      repo: DigithoBrasil/Aprecie
      branch: release
after_deploy:
- python manage.py test Aprecie.testes_de_fumaca