language: python
python:
- '3.3'
script:
- python manage.py makemigrations
- python manage.py migrate
- python manage.py test Login Reconhecimentos
- cd static
- npm install
- npm test
- cd ..
notifications:
  slack:
    secure: sGNzCxPD2NPZJiZ2zYda0tJfaRjQck5wUiK2uQmR5uVWkB5S9+iWPnl2pQkJt3LjlcuRzDAfRm44MNa8WL/VKiwUneEOmCk7dwooRmXavxLkh01UgkcRvXSr7xt+gW2mQNH4d/Q2JW6eAhHr/n3ffhDu8ZlzZfBpN9OljE/BeZRYGWqjaQ4dsbabFbidF+r44pLXN38Q7r5bkmCTm8hijQEUtrtnCcI8gZ1xOFAk/hmsxxTVFgiqgiExsyphdEJ5re+lmg9aDnsGk0iXsMgaFjaPpqqU1Eqyd45TFjKkmWPa4Dx4H7thlbbazObFUB539ygYqdG9PFJ5/llpsRYcLkp+jx8YJD6OcGnlavA8+aoWH9yZiJECb8hZVmNSuLyHx8WYpOvIHp6F7+rhwqOBTp8H8C0U5IDEACyV6LpGwvjPs8Fkh/MWaqKlHG/SFaqsoIDQbzufnxg959Rb2Jld0mQa6+IDrGC+e8xFVe2v1u4x5xthJWDzrAmB0t0HdtgSNb/+tRCMgDiCM0yIFNHoLxsFX02eXX2SRGLjmmRQY5jiMby1cH0jc6bnqgDpaBIvFG1uvTLrrP318v9UpZoCJVcjXVgp5DE0cJ4/PWL9PYgiuWVxl+D9i9nbrGvYviF9gdRDAsRX4ygUJb1wfHgtMWQKp+rtNI4LoltnmH4Sg7k=
deploy:
  provider: openshift
  user: gimoteco
  password:
    secure: lvH4oNalMA/R+Cr3/zGo7pgiEEQJ3coUJM1NTJ2W9kUre2PiJch7WtXxsD/Rne7MPK1xCjzi8iGinpFeE0QEjGuqsPNwRXJ7s+LfTdBdewfIwKHN2xAJkqQEQBccWPAlqizZjivHzfCUQV2Jo9rVmt8OhpWARbd4EOwRwQgAjXZSfO35sUGCCwclt955vz5innyM8zBoNHRuPvlbgHwsdgHGRRr712kYKJkrbCi+fvB3o/TuTdegUwLRoaHtPa8Pv25Qv/a8A8UVvSXtbGnEAGK+hhSnsrZrC5nKRTe2WsBQ7zHTTVa8XECL2MA8B8Lbgk9F92kPgk08Fz9HlLx5o5OhJkVA3hBvzu1mtqfwZAdF8FnnkQZY41dVkaiMk5MEBCM6j5ts8SxbnpC274tQj4V4gLjuOmrCyRwaxNtmOoh8SA0aJJCPt7y3jBlHVo2is3pgytLqppEJxhJrHDXQKNDUxxpQ/QLFYmhtbsmqXM7lDhGdEKMZklycuMxL4wqtIYbf/u9FB6QuZ6nJvp1MnHEydpJxgUyJaTwqDAfMeuUKteUSMDOeFaEzYE7ZY+zwmVv8oKAT1rprK8PLboOtX/CMk4G0diBqN1hSi1tQfb8SctkFxi/jPPDt5sG6ea0MHvJ6Z0y34q0kWdt7hUmSfbADQZYBBSUosMQw7nfmfJw=
  app: apreciestaging
  domain: cafecombytes
  on:
    repo: DigithoBrasil/Aprecie
after_deploy:
- python manage.py test Aprecie.testes_de_fumaca
