language: python
python:
- '3.3'
script:
- python manage.py makemigrations
- python manage.py migrate
- python manage.py test Login Reconhecimentos
- cd static
- npm install
- npm run sass
- npm test
- cd -
notifications:
  slack:
    secure: sGNzCxPD2NPZJiZ2zYda0tJfaRjQck5wUiK2uQmR5uVWkB5S9+iWPnl2pQkJt3LjlcuRzDAfRm44MNa8WL/VKiwUneEOmCk7dwooRmXavxLkh01UgkcRvXSr7xt+gW2mQNH4d/Q2JW6eAhHr/n3ffhDu8ZlzZfBpN9OljE/BeZRYGWqjaQ4dsbabFbidF+r44pLXN38Q7r5bkmCTm8hijQEUtrtnCcI8gZ1xOFAk/hmsxxTVFgiqgiExsyphdEJ5re+lmg9aDnsGk0iXsMgaFjaPpqqU1Eqyd45TFjKkmWPa4Dx4H7thlbbazObFUB539ygYqdG9PFJ5/llpsRYcLkp+jx8YJD6OcGnlavA8+aoWH9yZiJECb8hZVmNSuLyHx8WYpOvIHp6F7+rhwqOBTp8H8C0U5IDEACyV6LpGwvjPs8Fkh/MWaqKlHG/SFaqsoIDQbzufnxg959Rb2Jld0mQa6+IDrGC+e8xFVe2v1u4x5xthJWDzrAmB0t0HdtgSNb/+tRCMgDiCM0yIFNHoLxsFX02eXX2SRGLjmmRQY5jiMby1cH0jc6bnqgDpaBIvFG1uvTLrrP318v9UpZoCJVcjXVgp5DE0cJ4/PWL9PYgiuWVxl+D9i9nbrGvYviF9gdRDAsRX4ygUJb1wfHgtMWQKp+rtNI4LoltnmH4Sg7k=
deploy:
  - provider: openshift
    user: gimoteco@gmail.com
    password:
      secure: N053egusxOVYjmHVb+x02VZgpvP5PHI5WkL3YUSnzi4SkW6oW5os/N3ahbEtfy4e154nk88CPwkerdgds0sEX8zcn4AeXKOm0Baa7RK91SPtJIJybkp/UIswmlsCwDmVfnOQfeAtVzWdWVh1MqCJ55tK3SS1NYDUqTz34j7UVQ/oOyZTdkioBUzx0IFkSjMEd8+rw9x/pnOKGXcESyzHSxWqVsWSVJD9NdFH51zfr2rnFo3G291s1ERyBFrARICMrNQaC6gHCQIbJu+b52Z3DemUcZZnwZYwv54zxfZh5DTS5iIXlK3AW3N1mxY+MFQ0ZqEaqHBDmCOlRSRUnialMtwXG4j1+eL5ysgblLfr00jY23sC9LNcWRl5oecfujkbN438TAspqL2LpMZcGEYLakYSnIHXnB6ozt76T28sKjvq86UhcO0RHU4OCrCKgH6hB3QJQPR/5iY8Xzcx9uI2qZkIjWKldAhcsSINQDWA8dN1oyy29DRleBMtoC0VkgTrxcP8bcRwNiEwnuuirJm+vq89DOcQvOvCLF43XHlQbmRQ3ev2uUYjbzXrHri867Smf1eYxAErV6BTevQBr8BH7W6NIXlsF7sSvND3npR627BFPAMeQI8eWHM0C0d3UjroXteoL4hFp0kUeiuuusgwfbtkrxlqQaxBqz+wY2kx5q4=
    app: apreciestaging
    domain: cafecombytes
    on:
      repo: DigithoBrasil/Aprecie
      branch: master
  - provider: openshift
    user: gimoteco@gmail.com
    password:
      secure: GlQjglu4A9C57TGvbuSGqNqr8yN/aXENN2yvcCvxlMxoWd4beNLHAl977xpBh7a59z3OFNwXio5sxkXkgq8H/tUSQAS7h5kbAjEZNIxtm63HwWVpUBYZaL4LGXa+ZK/EqOhDI3pZcLd1FiwpRotidX8VpNqEsYEwTNQxHdp0M1yBP8qlYODThiwHcN8Lxs65ZLPeNqtAwp6CFzDAuF/5t3UtTg+rtpdZ7lpCZOzBJ7DJhtfKLkfWPOd+TrQXVpeEsg81I4C+lpjkh32j88UJUXEqqDEhOMAgOjmiEmczSfDb/doElWEdgO7Io5FBk3y+/wjNld5/R6r6cWyk0sqtBKdkqIIKgymvHuFKgZwbFX26hLeBuNrl54HX8TyoU0lmI7lU0KjViSBAylAKMT5J3c+8sGU2dzAeqxUeqbGLYK2WD8qZwFKalTRKIJD59BHamS+cAA9qo+ls+W+6FTu3hSOlYd8LUuHm8mwaNgi+bZZad1SGwwL9Ohka05ZwJZRHHzaHUnRpNDMRBpTJAsYsEAWnLZ38YhlifD+3sbMint446my+0gkK6vu29eDmHkSQVNCI6vfYrBM5g2W7Y6FyxR0YxCX/P5icoy2uo+NSaswlHo2NObnkmAyQjrjmh+8OCkLo7o/7l8MbL+04kN0nQrmcxqzwg4ug9kfQu8t5TdI=
    app: aprecie
    domain: cafecombytes
    on:
      repo: DigithoBrasil/Aprecie
      branch: release
after_deploy:
- python manage.py test Aprecie.testes_de_fumaca
